// src/terminal/commands/skills.ts
import type { CommandHandler } from '../commands';

export const skills: CommandHandler = () => ({ html: `
  <div class="cc-tool-use"><span class="cc-tool-dot">&#x23FA;</span><span class="cc-tool-name">Glob</span><span class="cc-tool-args">(skills/**)</span></div>
  <div class="cc-tool-result"><span class="cc-tool-result-sym">&#x2B0F;</span><span class="cc-tool-result-text">Found 34 skills</span></div>
  <div class="cc-output-block" style="font-size:12px;line-height:2;">

    <div style="color:var(--teal);margin-bottom:2px;">&#x251C;&#x2500;&#x2500; <strong>spoken-languages/</strong></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x251C;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">English</span><div class="skill-bar-bg"><div class="skill-bar" style="width:100%;background:var(--teal);"></div></div><span style="color:var(--overlay0);font-size:10px;">native</span></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x251C;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">French</span><div class="skill-bar-bg"><div class="skill-bar" style="width:100%;background:var(--teal);"></div></div><span style="color:var(--overlay0);font-size:10px;">native</span></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x251C;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">Kannada</span><div class="skill-bar-bg"><div class="skill-bar" style="width:70%;background:var(--teal);"></div></div><span style="color:var(--overlay0);font-size:10px;">conversational</span></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x251C;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">Hindi</span><div class="skill-bar-bg"><div class="skill-bar" style="width:40%;background:var(--teal);"></div></div><span style="color:var(--overlay0);font-size:10px;">basic</span></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x251C;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">Mandarin</span><div class="skill-bar-bg"><div class="skill-bar" style="width:40%;background:var(--teal);"></div></div><span style="color:var(--overlay0);font-size:10px;">basic</span></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x251C;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">German</span><div class="skill-bar-bg"><div class="skill-bar" style="width:40%;background:var(--teal);"></div></div><span style="color:var(--overlay0);font-size:10px;">basic</span></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x2514;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">Tamil</span><div class="skill-bar-bg"><div class="skill-bar" style="width:20%;background:var(--teal);"></div></div><span style="color:var(--overlay0);font-size:10px;">understand only</span></div>

    <div style="color:var(--blue);margin-bottom:2px;">&#x251C;&#x2500;&#x2500; <strong>languages/</strong></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x251C;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">JavaScript</span><div class="skill-bar-bg"><div class="skill-bar" style="width:80%;background:var(--blue);"></div></div></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x251C;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">TypeScript</span><div class="skill-bar-bg"><div class="skill-bar" style="width:80%;background:var(--blue);"></div></div></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x251C;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">Python</span><div class="skill-bar-bg"><div class="skill-bar" style="width:70%;background:var(--blue);"></div></div></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x251C;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">Java</span><div class="skill-bar-bg"><div class="skill-bar" style="width:60%;background:var(--blue);"></div></div></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x2514;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">Rust</span><div class="skill-bar-bg"><div class="skill-bar" style="width:20%;background:var(--blue);"></div></div><span style="color:var(--overlay0);font-size:10px;">learning</span></div>

    <div style="color:var(--mauve);margin-bottom:2px;">&#x251C;&#x2500;&#x2500; <strong>frontend/</strong></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x2514;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">React.js</span><div class="skill-bar-bg"><div class="skill-bar" style="width:70%;background:var(--mauve);"></div></div></div>

    <div style="color:var(--green);margin-bottom:2px;">&#x251C;&#x2500;&#x2500; <strong>backend/</strong></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x251C;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">Node.js</span><div class="skill-bar-bg"><div class="skill-bar" style="width:80%;background:var(--green);"></div></div></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x251C;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">Express</span><div class="skill-bar-bg"><div class="skill-bar" style="width:70%;background:var(--green);"></div></div></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x2514;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">Bun</span><div class="skill-bar-bg"><div class="skill-bar" style="width:80%;background:var(--green);"></div></div></div>

    <div style="color:var(--peach);margin-bottom:2px;">&#x251C;&#x2500;&#x2500; <strong>cloud/</strong></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x251C;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">AWS</span><div class="skill-bar-bg"><div class="skill-bar" style="width:50%;background:var(--peach);"></div></div></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x251C;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">Microsoft Azure</span><div class="skill-bar-bg"><div class="skill-bar" style="width:50%;background:var(--peach);"></div></div></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x2514;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">Google Cloud</span><div class="skill-bar-bg"><div class="skill-bar" style="width:50%;background:var(--peach);"></div></div></div>

    <div style="color:var(--sapphire);margin-bottom:2px;">&#x251C;&#x2500;&#x2500; <strong>data/</strong></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x251C;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">PostgreSQL</span><div class="skill-bar-bg"><div class="skill-bar" style="width:60%;background:var(--sapphire);"></div></div></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x251C;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">MongoDB</span><div class="skill-bar-bg"><div class="skill-bar" style="width:70%;background:var(--sapphire);"></div></div></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x251C;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">SQL</span><div class="skill-bar-bg"><div class="skill-bar" style="width:70%;background:var(--sapphire);"></div></div></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x2514;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">Machine Learning</span><div class="skill-bar-bg"><div class="skill-bar" style="width:40%;background:var(--sapphire);"></div></div><span style="color:var(--overlay0);font-size:10px;">learning</span></div>

    <div style="color:var(--lavender);margin-bottom:2px;">&#x251C;&#x2500;&#x2500; <strong>engineering/</strong></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x251C;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">Git</span><div class="skill-bar-bg"><div class="skill-bar" style="width:80%;background:var(--lavender);"></div></div></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x251C;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">Object-Oriented</span><div class="skill-bar-bg"><div class="skill-bar" style="width:70%;background:var(--lavender);"></div></div></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&#x2502;&nbsp;&nbsp;&nbsp;&#x2514;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">Computer Networks</span><div class="skill-bar-bg"><div class="skill-bar" style="width:60%;background:var(--lavender);"></div></div></div>

    <div style="color:var(--yellow);margin-bottom:2px;">&#x2514;&#x2500;&#x2500; <strong>soft-skills/</strong></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&nbsp;&nbsp;&nbsp;&nbsp;&#x251C;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">Project Management</span><div class="skill-bar-bg"><div class="skill-bar" style="width:40%;background:var(--yellow);"></div></div><span style="color:var(--overlay0);font-size:10px;">learning</span></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&nbsp;&nbsp;&nbsp;&nbsp;&#x251C;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">Problem Solving</span><div class="skill-bar-bg"><div class="skill-bar" style="width:80%;background:var(--yellow);"></div></div></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&nbsp;&nbsp;&nbsp;&nbsp;&#x251C;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">Team Collaboration</span><div class="skill-bar-bg"><div class="skill-bar" style="width:100%;background:var(--yellow);"></div></div></div>
    <div style="display:flex;align-items:center;gap:8px;"><span style="color:var(--overlay0);">&nbsp;&nbsp;&nbsp;&nbsp;&#x2514;&#x2500;&#x2500;</span><span style="color:var(--subtext0);min-width:160px;">Leadership</span><div class="skill-bar-bg"><div class="skill-bar" style="width:100%;background:var(--yellow);"></div></div></div>

  </div>
` });
